name: vvc
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - matplotlib
  - cudatoolkit=8
  - keras-gpu=2.1
  - pip
  - python=3.6
  - pip:
    - jsonpickle
    - opencv-python~=3.4
    - scikit-video~=1.1
    - glances
    - nvidia-ml-py3
    - ffmpeg-python~=0.1
