name: vvc
channels:
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=10.1
  - keras-gpu=2.1
  - jupyter
  - nomkl # The processing will be done by the GPU
  - matplotlib
  - pandas
  - pip
  - python=3.6
  - tensorflow-gpu=1.14
  - tqdm
  - pip:
    - ffmpeg-python~=0.1
    - glances
    - jsonpickle
    - nvidia-ml-py3
    - opencv-python~=3.4
    - scikit-video~=1.1
    - tensorflow_model_optimization
