name: vvc
channels:
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=9
  - keras-gpu=2.1
  - jupyter
  #- nomkl # For AMD Ryzen CPUs, prefer no MKL
  - matplotlib
  - pandas
  - pip
  - python=3.6
  - tqdm
  - pip:
    - ffmpeg-python~=0.1
    - glances
    - jsonpickle
    - nvidia-ml-py3
    - opencv-python~=3.4
    - scikit-video~=1.1
